export const DEFAULT_TAGS = [
  // Income
  { name: 'Salary',           type: 'income',  colorIndex: 1 },
  { name: 'Overtime Pay',     type: 'income',  colorIndex: 2 },
  { name: 'Passive Income',   type: 'income',  colorIndex: 3 },
  // Expense
  { name: 'Taxi Fee',         type: 'expense', colorIndex: 0 },
  { name: 'Food & Dining',    type: 'expense', colorIndex: 1 },
  { name: 'Groceries',        type: 'expense', colorIndex: 2 },
  { name: 'Transportation',   type: 'expense', colorIndex: 3 },
  { name: 'Fuel',             type: 'expense', colorIndex: 4 },
  { name: 'Rent',             type: 'expense', colorIndex: 5 },
  { name: 'Utilities',        type: 'expense', colorIndex: 6 },
  { name: 'Electricity',      type: 'expense', colorIndex: 7 },
  { name: 'Water Bill',       type: 'expense', colorIndex: 8 },
  { name: 'Internet',         type: 'expense', colorIndex: 9 },
  { name: 'Phone Bill',       type: 'expense', colorIndex: 0 },
  { name: 'Healthcare',       type: 'expense', colorIndex: 1 },
  { name: 'Medicine',         type: 'expense', colorIndex: 2 },
  { name: 'Insurance',        type: 'expense', colorIndex: 3 },
  { name: 'Education',        type: 'expense', colorIndex: 4 },
  { name: 'Entertainment',    type: 'expense', colorIndex: 5 },
  { name: 'Shopping',         type: 'expense', colorIndex: 6 },
  { name: 'Clothing',         type: 'expense', colorIndex: 7 },
  { name: 'Personal Care',    type: 'expense', colorIndex: 8 },
  { name: 'Gym',              type: 'expense', colorIndex: 9 },
  { name: 'Travel',           type: 'expense', colorIndex: 0 },
  { name: 'Hotel',            type: 'expense', colorIndex: 1 },
  { name: 'Dining Out',       type: 'expense', colorIndex: 2 },
  { name: 'Coffee',           type: 'expense', colorIndex: 3 },
  { name: 'Subscriptions',    type: 'expense', colorIndex: 4 },
  { name: 'Home Maintenance', type: 'expense', colorIndex: 5 },
  { name: 'Repairs',          type: 'expense', colorIndex: 6 },
  { name: 'Childcare',        type: 'expense', colorIndex: 7 },
  { name: 'Pet Care',         type: 'expense', colorIndex: 8 },
  { name: 'Donations',        type: 'expense', colorIndex: 9 },
  { name: 'Snacks',           type: 'expense', colorIndex: 0 },
];
